AgileApplications/Controllers/RolePermissionController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AgileApplications.Controllers
{
    public class RolePermissionController : Controller
    {
        RolePermissionManager rolePermissionManager = new RolePermissionManager(new EFRolePermissionRepository());
        public IActionResult Index()
        {
            var rolePermissionsWithRoles = rolePermissionManager.GetListRolePermissionWithRole();
            var rolePermissionWithPermissions = rolePermissionManager.GetListRolePermissionWithPermission();
            return View(rolePermissionsWithRoles);
        }

        [HttpGet]
        public IActionResult AddRolePermission()
        {
            RoleManager roleManager = new RoleManager(new EFRoleRepository());
            PermissionManager permissionManager = new PermissionManager(new EFPermissionRepository());

            List<SelectListItem> roleValues = (from x in roleManager.GetListRole()
                                               select new SelectListItem
                                               {
                                                   Text = x.Name,
                                                   Value = x.RoleId.ToString()
                                               }
                                               ).ToList();
            List<SelectListItem> permissionValues = (from x in permissionManager.GetListPermission()
                                                          select new SelectListItem
                                                          {
                                                              Text = x.Name,
                                                              Value = x.PermissionId.ToString()
                                                          }
                                                          ).ToList();
            ViewBag.roleValues = roleValues;
            ViewBag.permissionValues = permissionValues;
            return View();
        }

        [HttpPost]
        public IActionResult AddRolePermission(RolePermission rolePermission)
        {
            rolePermission.IsActive = true;
            rolePermission.CreatedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            rolePermission.ModifiedBy = rolePermission.CreatedBy;
            rolePermission.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            rolePermissionManager.AddRolePermission(rolePermission);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteRolePermission(int id)
        {
            var rolePermissionValue = rolePermissionManager.GetRolePermissionById(id);
            rolePermissionValue.IsActive = false;
            rolePermissionManager.UpdateRolePermission(rolePermissionValue);
            return RedirectToAction("Index");
        }

        [HttpGet] 
        public IActionResult EditRolePermission(int id)
        {
            RoleManager roleManager = new RoleManager(new EFRoleRepository());
            PermissionManager permissionManager = new PermissionManager(new EFPermissionRepository());

            List<SelectListItem> roleValues = (from x in roleManager.GetListRole()
                                               select new SelectListItem
                                               {
                                                   Text = x.Name,
                                                   Value = x.RoleId.ToString()
                                               }
                                               ).ToList();
            List<SelectListItem> permissionValues = (from x in permissionManager.GetListPermission()
                                                     select new SelectListItem
                                                     {
                                                         Text = x.Name,
                                                         Value = x.PermissionId.ToString()
                                                     }
                                                          ).ToList();
            ViewBag.roleValues = roleValues;
            ViewBag.permissionValues = permissionValues;
            var rolePermissionValues = rolePermissionManager.GetRolePermissionById(id);
            return View(rolePermissionValues);
        }

        [HttpPost]
        public IActionResult EditRolePermission(RolePermission rolePermission)
        {
            rolePermission.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            rolePermission.IsActive = true;
            rolePermissionManager.UpdateRolePermission(rolePermission);
            return RedirectToAction("Index");
        }
    }
}

AgileApplications/Views/RolePermission/AddRolePermission.cshtml
@model EntityLayer.Concrete.RolePermission
@{
    ViewData["Title"] = "AddRolePermission";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Add Role Permission</h1>

    @using (@Html.BeginForm("AddRolePermission", "RolePermission", FormMethod.Post))
    {
        @Html.Label("Role Name")
        @Html.DropDownListFor(x => x.RoleId, (List<SelectListItem>)ViewBag.roleValues, new {@class = "form-control"})
        <br />
        @Html.Label("Permission Name")
        @Html.DropDownListFor(x => x.PermissionId, (List<SelectListItem>)ViewBag.permissionValues, new {@class = "form-control"})
        <br />
        @Html.Label("Created By")
        @Html.TextBoxFor(x => x.CreatedBy, new {@class="form-control", @style="width: 300px"})
        <br />

        <button class="btn btn-primary" style="width: 300px">Save</button>
    }
</div>

AgileApplications/Views/RolePermission/EditRolePermission.cshtml
@model EntityLayer.Concrete.RolePermission
@{
    ViewData["Title"] = "EditRolePermission";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Edit Role Permission</h1>
    @using (Html.BeginForm("EditRolePermission", "RolePermission", FormMethod.Post))
    {
        @Html.Label("Role Permission ID")
        @Html.TextBoxFor(x => x.RolePermissionId, new {@class="form-control", @style="width: 300px"})
        @Html.Label("Role Name")
        @Html.DropDownListFor(x => x.RoleId, (List<SelectListItem>)ViewBag.roleValues, new {@class = "form-control"})
        @Html.Label("Permission Name")
        @Html.DropDownListFor(x => x.PermissionId, (List<SelectListItem>)ViewBag.permissionValues, new {@class = "form-control"})
        <br />
        @Html.HiddenFor(x => x.CreatedDate)
        @Html.HiddenFor(x => x.CreatedBy)
        @Html.HiddenFor(x => x.ModifiedBy)
        <button class="btn btn-secondary" style="width: 300px">Save</button>
    }

</div>

AgileApplications/Views/RolePermission/Index.cshtml
@using EntityLayer.Concrete
@model List<RolePermission>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div style="margin: 10px">
        <h1>Role Permission Page</h1>
        <a href="~/RolePermission/AddRolePermission" class="btn btn-primary" style="margin-bottom: 5px">Add New</a>
        <table class="table table-bordered">
            <tr>
                <th>RolePermissionID</th>
                <th>Role Name</th>
                <th>Permission Name</th>
                <th>IsActive</th>
                <th>CreatedBy</th>
                <th>CreatedDate</th>
                <th>ModifiedBy</th>
                <th>ModifiedDate</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.RolePermissionId</td>
                    <td>@item.Role.Name</td>
                    <td>@item.Permission.Name</td>
                    <td>@item.IsActive</td>
                    <td>@item.CreatedBy</td>
                    <td>@(((DateTime)item.CreatedDate).ToString("d"))</td>
                    <td>@item.ModifiedBy</td>
                    <td>@(((DateTime)item.ModifiedDate).ToString("d"))</td>
                    <td><a href="~/RolePermission/DeleteRolePermission/@item.RolePermissionId" class="btn btn-danger">Delete</a></td>
                    <td><a href="~/RolePermission/EditRolePermission/@item.RolePermissionId" class="btn btn-secondary">Update</a></td>
                </tr>
            }
        </table>
    </div>
</body>
</html>