AgileApplications/Controllers/PermissionController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace AgileApplications.Controllers
{
    public class PermissionController : Controller
    {
        PermissionManager permissionManager = new PermissionManager(new EFPermissionRepository());
        public IActionResult Index()
        {
            var values = permissionManager.GetListPermission();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddPermission()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddPermission(Permission permission)
        {
            PermissionValidator permissionValidor = new PermissionValidator();
            ValidationResult result = permissionValidor.Validate(permission);
            
            if(result.IsValid)
            {
                permission.IsActive = true;
                permission.CreatedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                permission.ModifiedBy = permission.CreatedBy;
                permission.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                return RedirectToAction("Index");
            } else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }
            }
            return View();
        }

        public IActionResult DeletePermission(int id)
        {
            var permissionvalue = permissionManager.GetPermissionById(id);
            permissionvalue.IsActive = false;
            permissionManager.UpdatePermission(permissionvalue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditPermission(int id)
        {
            var permissionValues = permissionManager.GetPermissionById(id);
            return View(permissionValues);
        }

        [HttpPost]
        public IActionResult EditPermission(Permission permission)
        {
            permission.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            permission.IsActive = true;
            permissionManager.UpdatePermission(permission);
            return RedirectToAction("Index");
        }
    }
}

AgileApplications/Views/Permission/AddPermission.cshtml
@model EntityLayer.Concrete.Permission
@{
    ViewData["Title"] = "AddPermission";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Add Permission</h1>

    @using (@Html.BeginForm("AddPermission", "Permission", FormMethod.Post))
    {
        @Html.Label("Permission Name")
        @Html.TextBoxFor(x => x.Name, new {@class="form-control", @style="width: 300px"})
        @Html.ValidationMessageFor(x => x.Name, null, new {@style="color: red"})
        <br />

        @Html.Label("Created By")
        @Html.TextBoxFor(x => x.CreatedBy, new {@class="form-control", @style="width: 300px"})
        <br />

        <button class="btn btn-primary" style="width: 300px">Save</button>
    }
</div>

AgileApplications/Views/Permission/EditPermission.cshtml
@model EntityLayer.Concrete.Permission
@{
    ViewData["Title"] = "EditPermission";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Edit Permission</h1>
    @using (Html.BeginForm("EditPermission", "Permission", FormMethod.Post))
    {
        @Html.Label("Permission ID")
        @Html.TextBoxFor(x => x.PermissionId, new {@class = "form-control", @style = "width: 300px"})
        @Html.Label("Permission Name")
        @Html.TextBoxFor(x => x.Name, new {@class = "form-control", @style = "width: 300px"})
        <br />
        @Html.HiddenFor(x => x.CreatedDate)
        @Html.HiddenFor(x => x.CreatedBy)
        @Html.HiddenFor(x => x.ModifiedBy)
        <button class="btn btn-secondary" style="width: 300px">Save</button>
    }

</div>

AgileApplications/Views/Permission/Index.cshtml
@using EntityLayer.Concrete
@model List<Permission>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div style="margin: 10px">
        <h1>Permission Page</h1>
        <a href="~/Permission/AddPermission" class="btn btn-primary" style="margin-bottom: 5px">Add New</a>
        <table class="table table-bordered">
            <tr>
                <th>PermissionID</th>
                <th>Name</th>
                <th>IsActive</th>
                <th>CreatedBy</th>
                <th>CreatedDate</th>
                <th>ModifiedBy</th>
                <th>ModifiedDate</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.PermissionId</td>
                    <td>@item.Name</td>
                    <td>@item.IsActive</td>
                    <td>@item.CreatedBy</td>
                    <td>@(((DateTime)item.CreatedDate).ToString("d"))</td>
                    <td>@item.ModifiedBy</td>
                    <td>@(((DateTime)item.ModifiedDate).ToString("d"))</td>
                    <td><a href="~/Permission/DeletePermission/@item.PermissionId" class="btn btn-danger">Delete</a></td>
                    <td><a href="~/Permission/EditPermission/@item.PermissionId" class="btn btn-secondary">Update</a></td>
                </tr>
            }
        </table>
    </div>
</body>
</html>