AgileApplications/Controllers/ScrumTeamController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace AgileApplications.Controllers
{
    public class ScrumTeamController : Controller
    {
        ScrumTeamManager scrumTeamManager = new ScrumTeamManager(new EFScrumTeamRepository());
        public IActionResult Index()
        {
            var values = scrumTeamManager.GetListScrumTeam();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddScrumTeam()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddScrumTeam(ScrumTeam scrumTeam)
        {
            ScrumTeamValidator scrumTeamValidator = new ScrumTeamValidator();
            ValidationResult result = scrumTeamValidator.Validate(scrumTeam);
            if(result.IsValid)
            {
                scrumTeam.IsActive = true;
                scrumTeam.CreatedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                scrumTeam.ModifiedBy = scrumTeam.CreatedBy;
                scrumTeam.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                scrumTeamManager.AddScrumTeam(scrumTeam);
                return RedirectToAction("Index");
            } else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }
            }
            return View();
        }

        public IActionResult DeleteScrumTeam(int id)
        {
            var scrumTeamValue = scrumTeamManager.GetScrumTeamById(id);
            scrumTeamValue.IsActive = false;
            scrumTeamManager.UpdateScrumTeam(scrumTeamValue);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult EditScrumTeam(int id)
        {
            var scrumTeamValues = scrumTeamManager.GetScrumTeamById(id);
            return View(scrumTeamValues);
        }

        [HttpPost]
        public IActionResult EditScrumTeam(ScrumTeam scrumTeam)
        {
            scrumTeam.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            scrumTeam.IsActive = true;
            scrumTeamManager.UpdateScrumTeam(scrumTeam);
            return RedirectToAction("Index");
        }

    }
}

AgileApplications/Views/ScrumTeam/AddScrumTeam.cshtml
@model EntityLayer.Concrete.ScrumTeam
@{
    ViewData["Title"] = "AddScrumTeam";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Add Scrum Team</h1>

    @using (@Html.BeginForm("AddScrumTeam", "ScrumTeam", FormMethod.Post))
    {
        @Html.Label("Scrum Team Name")
        @Html.TextBoxFor(x => x.Name, new {@class="form-control", @style="width: 300px"})
        @Html.ValidationMessageFor(x => x.Name, null, new {@style="color: red"})
        <br />

        @Html.Label("Created By")
        @Html.TextBoxFor(x => x.CreatedBy, new {@class="form-control", @style="width: 300px"})
        <br />

        <button class="btn btn-primary" style="width: 300px">Save</button>
    }
</div>

AgileApplications/Views/ScrumTeam/EditScrumTeam.cshtml
@model EntityLayer.Concrete.ScrumTeam
@{
    ViewData["Title"] = "EditSrumTeam";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Edit Scrum Team</h1>
    @using (Html.BeginForm("EditScrumTeam", "ScrumTeam", FormMethod.Post))
    {
        @Html.Label("Role ID")
        @Html.TextBoxFor(x => x.ScrumTeamId, new {@class = "form-control", @style = "width: 300px"})
        @Html.Label("Role Name")
        @Html.TextBoxFor(x => x.Name, new {@class = "form-control", @style = "width: 300px"})
        <br />
        @Html.HiddenFor(x => x.CreatedDate)
        @Html.HiddenFor(x => x.CreatedBy)
        @Html.HiddenFor(x => x.ModifiedBy)
        <button class="btn btn-secondary" style="width: 300px">Save</button>
    }

</div>

AgileApplications/Views/ScrumTeam/Index.cshtml
@using EntityLayer.Concrete
@model List<ScrumTeam>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div style="margin: 10px">
        <h1>ScrumTeam Page</h1>
        <a href="~/ScrumTeam/AddScrumTeam/" class="btn btn-primary" style="margin-bottom: 5px">Add New</a>
        <table class="table table-bordered">
            <tr>
                <th>ScrumTeamID</th>
                <th>Name</th>
                <th>IsActive</th>
                <th>CreatedBy</th>
                <th>CreatedDate</th>
                <th>ModifiedBy</th>
                <th>ModifiedDate</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ScrumTeamId</td>
                    <td>@item.Name</td>
                    <td>@item.IsActive</td>
                    <td>@item.CreatedBy</td>
                    <td>@(((DateTime)item.CreatedDate).ToString("d"))</td>
                    <td>@item.ModifiedBy</td>
                    <td>@(((DateTime)item.ModifiedDate).ToString("d"))</td>
                    <td><a href="~/ScrumTeam/DeleteScrumTeam/@item.ScrumTeamId" class="btn btn-danger">Delete</a></td>
                    <td><a href="~/ScrumTeam/EditScrumTeam/@item.ScrumTeamId" class="btn btn-secondary">Update</a></td>
                </tr>
            }
        </table>
    </div>
</body>
</html>