AgileApplications/Controllers/SprintController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AgileApplications.Controllers
{
    public class SprintController : Controller
    {
        SprintManager sprintManager = new SprintManager(new EFSprintRepository());
        public IActionResult Index()
        {
            var sprintWithScrumTeam = sprintManager.GetListSprintWithScrumTeam();
            return View(sprintWithScrumTeam);
        }

        [HttpGet]
        public IActionResult AddSprint()
        {
            ScrumTeamManager scrumTeamManager = new ScrumTeamManager(new EFScrumTeamRepository());

            List<SelectListItem> scrumTeamValues = (from x in scrumTeamManager.GetListScrumTeam()
                                                    select new SelectListItem
                                                    {
                                                        Text = x.Name,
                                                        Value = x.ScrumTeamId.ToString()
                                                    }
                                                 ).ToList();

            ViewBag.scrumTeamValues = scrumTeamValues;
            return View();
        }

        [HttpPost]
        public IActionResult AddSprint(Sprint sprint)
        {
            SprintValidator sprintValidator = new SprintValidator();
            ValidationResult result = sprintValidator.Validate(sprint);
            sprint.IsActive = true;
            if (result.IsValid)
            {
                sprint.CreatedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                sprint.ModifiedBy = sprint.CreatedBy;
                sprint.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                sprintManager.AddSprint(sprint);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }
            }
            return View();

        }

        public IActionResult DeleteSprint(int id)
        {
            var sprintValue = sprintManager.GetSprintById(id);
            sprintValue.IsActive = false;
            sprintManager.UpdateSprint(sprintValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSprint(int id)
        {
            var sprintValue = sprintManager.GetSprintById(id);
            ScrumTeamManager scrumTeamManager = new ScrumTeamManager(new EFScrumTeamRepository());

            List<SelectListItem> scrumTeamValues = (from x in scrumTeamManager.GetListScrumTeam()
                                                    select new SelectListItem
                                                    {
                                                        Text = x.Name,
                                                        Value = x.ScrumTeamId.ToString()
                                                    }
                                                 ).ToList();

            ViewBag.scrumTeamValues = scrumTeamValues;
            return View(sprintValue);
        }
        [HttpPost]
        public IActionResult EditSprint(Sprint sprint)
        {
            sprint.ModifiedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            sprint.IsActive = true;
            sprintManager.UpdateSprint(sprint);
            return RedirectToAction("Index");
        }
    }
}

AgileApplications/Views/Sprint/AddSprint.cshtml
@model EntityLayer.Concrete.Sprint
@{
    ViewData["Title"] = "AddSprint";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Add Sprint</h1>

    @using (@Html.BeginForm("AddSprint", "Sprint", FormMethod.Post))
    {
        @Html.Label("Name")
        @Html.TextBoxFor(x => x.Name, new {@class="form-control", @style="width: 300px"})
        @Html.ValidationMessageFor(x => x.Name, null, new {@style="color: red"})
        <br />

        @Html.Label("Scrum Team Name")
        @Html.DropDownListFor(x => x.ScrumTeamId, (List<SelectListItem>)ViewBag.scrumTeamValues, new {@class = "form-control"})
        <br />

        @Html.Label("Start Date")
        @Html.TextBoxFor(x => x.StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @placeholder = "dd-mm-yyyy", @style="width: 300px"})
        @Html.ValidationMessageFor(x => x.StartDate, null, new {@style="color: red"})
        <br />

        @Html.Label("End Date")
        @Html.TextBoxFor(x => x.EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @placeholder = "dd-mm-yyyy", @style="width: 300px"})
        @Html.ValidationMessageFor(x => x.EndDate, null, new {@style="color: red"})
        <br />

        @Html.Label("Created By")
        @Html.TextBoxFor(x => x.CreatedBy, new {@class="form-control", @style="width: 300px"})
        <br />
        <button class="btn btn-primary" style="width: 300px">Save</button>
    }
</div>

AgileApplications/Views/Sprint/EditSprint.cshtml
@model EntityLayer.Concrete.Sprint
@{
    ViewData["Title"] = "EditSprint";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <h1>Edit Scrum Team</h1>
    @using (Html.BeginForm("EditSprint", "Sprint", FormMethod.Post))
    {
        @Html.Label("Sprint ID")
        @Html.TextBoxFor(x => x.SprintId, new {@class="form-control", @style="width: 300px"})
        <br />
        @Html.Label("Sprint Name")
        @Html.TextBoxFor(x => x.Name, new {@class="form-control", @style="width: 300px"})
        <br />
        @Html.Label("Scrum Team Name")
        @Html.DropDownListFor(x => x.ScrumTeamId, (List<SelectListItem>)ViewBag.scrumTeamValues, new {@class = "form-control"})
        <br />
        @Html.Label("Start Date")
        @Html.TextBoxFor(x => x.StartDate, new {@class="form-control", @style="width: 300px"})
        <br />
        @Html.Label("End Date")
        @Html.TextBoxFor(x => x.EndDate, new {@class="form-control", @style="width: 300px"})
        <br />
        @Html.HiddenFor(x => x.CreatedDate)
        @Html.HiddenFor(x => x.CreatedBy)
        @Html.HiddenFor(x => x.ModifiedBy)
        <button class="btn btn-secondary" style="width: 300px">Save</button>
    }

</div>

AgileApplications/Views/Sprint/Index.cshtml
@using EntityLayer.Concrete
@model List<Sprint>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div style="margin: 10px">
        <h1>Sprint Page</h1>
        <a href="~/Sprint/AddSprint/" class="btn btn-primary" style="margin-bottom: 5px">Add New</a>
        <table class="table table-bordered">
            <tr>
                <th>SprintID</th>
                <th>Scrum Team Name</th>
                <th>Name</th>
                <th>StartDate</th>
                <th>EndDate</th>
                <th>IsActive</th>
                <th>CreatedBy</th>
                <th>CreatedDate</th>
                <th>ModifiedBy</th>
                <th>ModifiedDate</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.SprintId</td>
                    <td>@item.ScrumTeam.Name</td>
                    <td>@item.Name</td>
                    <td>@(((DateTime)item.StartDate).ToString("d"))</td>
                    <td>@(((DateTime)item.EndDate).ToString("d"))</td>
                    <td>@item.IsActive</td>
                    <td>@item.CreatedBy</td>
                    <td>@(((DateTime)item.CreatedDate).ToString("d"))</td>
                    <td>@item.ModifiedBy</td>
                    <td>@(((DateTime)item.ModifiedDate).ToString("d"))</td>
                    <td><a href="~/Sprint/DeleteSprint/@item.SprintId" class="btn btn-danger">Delete</a></td>
                    <td><a href="~/Sprint/EditSprint/@item.SprintId" class="btn btn-danger" class="btn btn-secondary">Update</a></td>
                </tr>
            }
        </table>
    </div>
</body>
</html>